import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    AUTH_SECRET: z.string().min(32),
    AUTH_URL: z.string().url().optional(),
    AUTH_GOOGLE_ID: z.string().min(1),
    AUTH_GOOGLE_SECRET: z.string().min(1),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
    DODO_PAYMENTS_API_KEY: z.string().min(1),
    DODO_WEBHOOK_KEY: z.string().min(1),
    DODO_TOPUP_PRODUCT_ID: z.string().min(1),
    DODO_ENVIRONMENT: z.enum(["test_mode", "live_mode"]).default("test_mode"),
    HELIUS_RPC_URL: z.string().url(),
    HELIUS_API_KEY: z.string().optional(),
    HELIUS_WEBHOOK_ID: z.string().optional(),
    HELIUS_WEBHOOK_AUTH_TOKEN: z.string().optional(),
    TREASURY_SECRET_KEY: z.string().min(1),
    TREASURY_PUBLIC_KEY: z.string().min(32).max(44),
    STABLECOIN_MINT: z.string().min(32).max(44),
    STABLECOIN_DECIMALS: z.coerce.number().int().min(0).max(18).default(6),
    ADMIN_API_TOKEN: z.string().min(32).optional(),
    // Lose this and every encrypted balance is unrecoverable. Required.
    UMBRA_AGENT_SEED_SECRET: z.string().min(32),
    UMBRA_NETWORK: z.enum(["devnet", "mainnet", "localnet"]).default("devnet"),
    UMBRA_RPC_SUBSCRIPTIONS_URL: z.string().url().optional(),
    UMBRA_INDEXER_URL: z.string().url().optional(),
    UMBRA_RELAYER_URL: z.string().url().optional(),
    DEMO_AGENT_API_KEY: z.string().min(1).optional(),
    DEMO_MERCHANT_URL: z.string().url().optional(),
    CRON_SECRET: z.string().min(16).optional(),
  },

  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_SOLANA_CLUSTER: z
      .enum(["mainnet-beta", "devnet"])
      .default("devnet"),
  },

  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_URL: process.env.AUTH_URL,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    DODO_PAYMENTS_API_KEY: process.env.DODO_PAYMENTS_API_KEY,
    DODO_WEBHOOK_KEY: process.env.DODO_WEBHOOK_KEY,
    DODO_TOPUP_PRODUCT_ID: process.env.DODO_TOPUP_PRODUCT_ID,
    DODO_ENVIRONMENT: process.env.DODO_ENVIRONMENT,
    HELIUS_RPC_URL: process.env.HELIUS_RPC_URL,
    HELIUS_API_KEY: process.env.HELIUS_API_KEY,
    HELIUS_WEBHOOK_ID: process.env.HELIUS_WEBHOOK_ID,
    HELIUS_WEBHOOK_AUTH_TOKEN: process.env.HELIUS_WEBHOOK_AUTH_TOKEN,
    TREASURY_SECRET_KEY: process.env.TREASURY_SECRET_KEY,
    TREASURY_PUBLIC_KEY: process.env.TREASURY_PUBLIC_KEY,
    STABLECOIN_MINT: process.env.STABLECOIN_MINT,
    STABLECOIN_DECIMALS: process.env.STABLECOIN_DECIMALS,
    ADMIN_API_TOKEN: process.env.ADMIN_API_TOKEN,
    UMBRA_AGENT_SEED_SECRET: process.env.UMBRA_AGENT_SEED_SECRET,
    UMBRA_NETWORK: process.env.UMBRA_NETWORK,
    UMBRA_RPC_SUBSCRIPTIONS_URL: process.env.UMBRA_RPC_SUBSCRIPTIONS_URL,
    UMBRA_INDEXER_URL: process.env.UMBRA_INDEXER_URL,
    UMBRA_RELAYER_URL: process.env.UMBRA_RELAYER_URL,
    CRON_SECRET: process.env.CRON_SECRET,
    DEMO_AGENT_API_KEY: process.env.DEMO_AGENT_API_KEY,
    DEMO_MERCHANT_URL: process.env.DEMO_MERCHANT_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SOLANA_CLUSTER: process.env.NEXT_PUBLIC_SOLANA_CLUSTER,
  },

  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
